// <auto-generated />
namespace AtTheMovies.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddConcurrencyChecks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddConcurrencyChecks));
        
        string IMigrationMetadata.Id
        {
            get { return "201408261644127_AddConcurrencyChecks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
